name: flutter_counter
description: Example BLoC Counter App
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  google_fonts: ^3.0.1
  hydrated_bloc: ^9.0.0
  json_annotation: ^4.7.0
  path_provider: ^2.0.11
  weather_repository:
    path: packages/weather_repository

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: any
  flutter_test:
    sdk: flutter
  json_serializable: ^6.5.4
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
