name: weather_repository
description: A new Flutter package project.
version: 0.0.1
publish_to: none
homepage:

environment:
  sdk: ">=2.18.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.5
  json_annotation: ^4.7.0
  open_meteo_api:
    path: ../open_meteo_api

dev_dependencies:
  build_runner: ^2.3.3
  coverage: ^1.6.2
  json_serializable: ^6.5.4
  mocktail: ^0.3.0
  test: ^1.22.2
  very_good_analysis: ^3.1.0
flutter:
